### ISSUE TITLE
500错误及通信失败

### ISSUE THREAD

**Issue by Suevan** [daxingplay/dokuwiki-plugin-authucenter#1]
首先感谢作者分享。
但是使用这个插件，在后台启用“Authucenter”验证方式后，马上就会500错误。
然后我手动把插件里面的 “api” "uc_client"复制到根目录后，500错误消失，但是UC通信仍然失败。不知道该如何解决。是否是插件里的目录定义有错误？
我也用早期版本dokuwiki使用了早期的插件，但是也是会出现500错误。
我用的是lnmp。希望作者有空的话可以测试一下。谢谢。

**Comment by daxingplay** [comment]
打开 PHP error log，把 error 贴出来看看？

**Comment by Suevan** [comment]
后台设置完成后出现以下错误提示：
`[11-Dec-2017 21:51:07 PRC] PHP Warning:  Declaration of auth_plugin_authucenter::getUserData($user) should be compatible with DokuWiki_Auth_Plugin::getUserData($user, $requireGroups = true) in /home/wwwroot/namelessegg.com/lib/plugins/authucenter/auth.php on line 13
[11-Dec-2017 21:51:07 PRC] PHP Fatal error:  Uncaught Error: Call to undefined function uc_user_synlogout() in /home/wwwroot/namelessegg.com/lib/plugins/authucenter/auth.php:70
Stack trace:
#0 /home/wwwroot/namelessegg.com/inc/auth.php(551): auth_plugin_authucenter->logOff()
#1 /home/wwwroot/namelessegg.com/inc/auth.php(70): auth_logoff()
#2 /home/wwwroot/namelessegg.com/inc/init.php(222): auth_setup()
#3 /home/wwwroot/namelessegg.com/doku.php(34): require_once('/home/wwwroot/n...')
#4 {main}
  thrown in /home/wwwroot/namelessegg.com/lib/plugins/authucenter/auth.php on line 70
[11-Dec-2017 21:51:09 PRC] PHP Warning:  Declaration of auth_plugin_authucenter::getUserData($user) should be compatible with DokuWiki_Auth_Plugin::getUserData($user, $requireGroups = true) in /home/wwwroot/namelessegg.com/lib/plugins/authucenter/auth.php on line 13
[11-Dec-2017 21:51:09 PRC] PHP Fatal error:  Uncaught Error: Call to undefined function uc_user_synlogout() in /home/wwwroot/namelessegg.com/lib/plugins/authucenter/auth.php:70
Stack trace:
#0 /home/wwwroot/namelessegg.com/inc/auth.php(551): auth_plugin_authucenter->logOff()
#1 /home/wwwroot/namelessegg.com/inc/auth.php(70): auth_logoff()
#2 /home/wwwroot/namelessegg.com/inc/init.php(222): auth_setup()
#3 /home/wwwroot/namelessegg.com/doku.php(34): require_once('/home/wwwroot/n...')
#4 {main}
  thrown in /home/wwwroot/namelessegg.com/lib/plugins/authucenter/auth.php on line 70`
